import type { AppSet, AppGet } from '../appStore.types';
import type { Collection, SmartQuery, AssetTag, AssetMetadata, TaggingMode } from '@/types/collections';
import { evaluateSmartQuery } from '@/utils/smartQueryEvaluator';
import { analyzeAssetRecord } from '@/features/assets/assetAnalysis';

/** Coerce an AssetRecord timestamp (ISO string, or epoch ms) to epoch ms. */
function toEpochMs(value: unknown): number | undefined {
  if (typeof value === 'number') return value;
  if (typeof value !== 'string') return undefined;
  const parsed = new Date(value).getTime();
  return Number.isNaN(parsed) ? undefined : parsed;
}

/** Order-sensitive id comparison, used to skip no-op smart-collection writes. */
function sameIds(a: readonly string[], b: readonly string[]): boolean {
  return a.length === b.length && a.every((id, i) => id === b[i]);
}

export const collectionsInitialState = {
  collections: [] as Collection[],
  assetMetadata: new Map<string, AssetMetadata>(),
  availableTags: [] as AssetTag[],
  taggingMode: 'on-generation' as TaggingMode,
  taggingQueue: [] as string[],
  activeCollectionId: null as string | null,
};

export function createCollectionsActions(set: AppSet, get: AppGet) {
  return {
    createCollection: (params: { name: string; type: Collection['type']; smartQuery?: SmartQuery; isAutoGenerated?: boolean }) =>
      set((state) => ({
        collections: [...state.collections, {
          id: crypto.randomUUID(),
          name: params.name,
          type: params.type,
          assetIds: [],
          smartQuery: params.smartQuery,
          tagIds: [],
          isAutoGenerated: params.isAutoGenerated ?? false,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        } as Collection],
      })),

    deleteCollection: (id: string) =>
      set((state) => ({
        collections: state.collections.filter(c => c.id !== id),
      })),

    renameCollection: (id: string, name: string) =>
      set((state) => ({
        collections: state.collections.map(c => c.id === id ? { ...c, name, updatedAt: Date.now() } : c),
      })),

    addAssetToCollection: (collectionId: string, assetId: string) =>
      set((state) => ({
        collections: state.collections.map(c =>
          c.id === collectionId && !c.assetIds.includes(assetId)
            ? { ...c, assetIds: [...c.assetIds, assetId], updatedAt: Date.now() }
            : c
        ),
      })),

    removeAssetFromCollection: (collectionId: string, assetId: string) =>
      set((state) => ({
        collections: state.collections.map(c =>
          c.id === collectionId
            ? { ...c, assetIds: c.assetIds.filter(a => a !== assetId), updatedAt: Date.now() }
            : c
        ),
      })),

    createSmartCollection: (params: { name: string; smartQuery: SmartQuery; isAutoGenerated?: boolean }) =>
      get().createCollection({ name: params.name, type: 'smart', smartQuery: params.smartQuery, isAutoGenerated: params.isAutoGenerated ?? true }),

    refreshSmartCollection: (id: string) => {
      const collection = get().collections.find(c => c.id === id);
      if (!collection || collection.type !== 'smart' || !collection.smartQuery) return;

      const matchedAssetIds: string[] = [];
      const metadata = get().assetMetadata;

      for (const asset of get().assetLibrary) {
        const generationContext = {
          prompt: asset.prompt,
          model: asset.model,
          createdAt: toEpochMs(asset.createdAt),
        };
        if (evaluateSmartQuery(collection.smartQuery!, generationContext, metadata.get(asset.id))) {
          matchedAssetIds.push(asset.id);
        }
      }

      set((state) => ({
        collections: state.collections.map(c =>
          c.id === id ? { ...c, assetIds: matchedAssetIds, updatedAt: Date.now() } : c
        ),
      }));
    },

    /**
     * Re-evaluate every smart collection against the current library and
     * metadata. Manual collections are hand-curated and are never touched.
     */
    refreshAllSmartCollections: () => {
      const { collections, assetLibrary, assetMetadata } = get();
      if (!collections.some((c) => c.type === 'smart')) return;

      const now = Date.now();
      set({
        collections: collections.map((collection) => {
          if (collection.type !== 'smart' || !collection.smartQuery) return collection;

          const matchedAssetIds = assetLibrary
            .filter((asset) =>
              evaluateSmartQuery(
                collection.smartQuery!,
                {
                  prompt: asset.prompt,
                  model: asset.model,
                  createdAt: toEpochMs(asset.createdAt),
                },
                assetMetadata.get(asset.id),
              ),
            )
            .map((asset) => asset.id);

          return sameIds(collection.assetIds, matchedAssetIds)
            ? collection
            : { ...collection, assetIds: matchedAssetIds, updatedAt: now };
        }),
      });
    },

    /**
     * Analyse the given assets now, storing the derived metadata, publishing the
     * new tags to `availableTags`, clearing them from the backlog, and
     * re-evaluating smart collections against the fresh metadata.
     *
     * Analysis is deterministic and synchronous (see `assetAnalysis`), so there
     * is no in-flight phase to model - an asset is either analysed or queued.
     */
    analyzeAssets: (assetIds: string[]) => {
      const { assetLibrary, assetMetadata, availableTags } = get();
      const targets = assetIds
        .map((id) => assetLibrary.find((asset) => asset.id === id))
        .filter((asset): asset is NonNullable<typeof asset> => Boolean(asset));

      if (targets.length === 0) {
        // Still clear the requested ids from the backlog: an id with no asset
        // behind it (deleted mid-queue) must not wedge the queue forever.
        const requested = new Set(assetIds);
        set((state) => ({
          taggingQueue: state.taggingQueue.filter((id) => !requested.has(id)),
        }));
        return;
      }

      const nextMetadata = new Map(assetMetadata);
      const knownTagIds = new Set(availableTags.map((tag) => tag.id));
      const newTags: AssetTag[] = [];

      for (const asset of targets) {
        const metadata = analyzeAssetRecord(asset);
        nextMetadata.set(asset.id, metadata);
        for (const tag of metadata.tags) {
          if (knownTagIds.has(tag.id)) continue;
          knownTagIds.add(tag.id);
          // The registry entry is the tag itself, not its per-asset weight.
          newTags.push({ ...tag, confidence: 1 });
        }
      }

      const analyzed = new Set(targets.map((asset) => asset.id));
      set((state) => ({
        assetMetadata: nextMetadata,
        availableTags: newTags.length > 0 ? [...state.availableTags, ...newTags] : state.availableTags,
        taggingQueue: state.taggingQueue.filter((id) => !analyzed.has(id)),
      }));

      get().refreshAllSmartCollections();
    },

    /** Analyse every library asset that has no metadata yet. */
    analyzeUntaggedAssets: () => {
      const { assetLibrary, assetMetadata } = get();
      const untagged = assetLibrary
        .filter((asset) => !assetMetadata.has(asset.id))
        .map((asset) => asset.id);
      if (untagged.length === 0) return;
      get().analyzeAssets(untagged);
    },

    /**
     * Route newly-arrived assets according to the user's tagging mode. This is
     * the single entry point generation uses, so the Settings choice actually
     * governs behaviour instead of being written and never read.
     */
    enqueueForTagging: (assetIds: string[]) => {
      const { taggingMode, assetMetadata, taggingQueue } = get();
      if (taggingMode === 'off') return;

      const pending = assetIds.filter((id) => !assetMetadata.has(id));
      if (pending.length === 0) return;

      if (taggingMode === 'on-generation') {
        get().analyzeAssets(pending);
        return;
      }

      // 'on-demand' and 'background-batch' both defer; the difference is who
      // drains the backlog (the Analyze control vs. the background pass).
      const queued = new Set(taggingQueue);
      const additions = pending.filter((id) => !queued.has(id));
      if (additions.length === 0) return;
      set((state) => ({ taggingQueue: [...state.taggingQueue, ...additions] }));
    },

    setTaggingMode: (mode: TaggingMode) => set({ taggingMode: mode }),

    addUserTag: (tag: AssetTag) =>
      set((state) => ({
        availableTags: [...state.availableTags, { ...tag, source: 'user' as const }],
      })),

    removeUserTag: (tagId: string) =>
      set((state) => ({
        availableTags: state.availableTags.filter(t => !(t.id === tagId && t.source === 'user')),
      })),

    setActiveCollection: (id: string | null) => set({ activeCollectionId: id }),
  };
}