import type { AppSet, AppGet } from '../appStore.types';
import type { Collection, SmartQuery, AssetTag, AssetMetadata, TaggingMode } from '@/types/collections';
import { evaluateSmartQuery } from '@/utils/smartQueryEvaluator';

export const collectionsInitialState = {
  collections: [] as Collection[],
  assetMetadata: new Map<string, AssetMetadata>(),
  availableTags: [] as AssetTag[],
  taggingMode: 'on-generation' as TaggingMode,
  taggingQueue: [] as string[],
  activeCollectionId: null as string | null,
};

export function createCollectionsActions(set: AppSet, get: AppGet) {
  return {
    createCollection: (params: { name: string; type: Collection['type']; smartQuery?: SmartQuery; isAutoGenerated?: boolean }) =>
      set((state) => ({
        collections: [...state.collections, {
          id: crypto.randomUUID(),
          name: params.name,
          type: params.type,
          assetIds: [],
          smartQuery: params.smartQuery,
          tagIds: [],
          isAutoGenerated: params.isAutoGenerated ?? false,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        } as Collection],
      })),

    deleteCollection: (id: string) =>
      set((state) => ({
        collections: state.collections.filter(c => c.id !== id),
      })),

    renameCollection: (id: string, name: string) =>
      set((state) => ({
        collections: state.collections.map(c => c.id === id ? { ...c, name, updatedAt: Date.now() } : c),
      })),

    addAssetToCollection: (collectionId: string, assetId: string) =>
      set((state) => ({
        collections: state.collections.map(c =>
          c.id === collectionId && !c.assetIds.includes(assetId)
            ? { ...c, assetIds: [...c.assetIds, assetId], updatedAt: Date.now() }
            : c
        ),
      })),

    removeAssetFromCollection: (collectionId: string, assetId: string) =>
      set((state) => ({
        collections: state.collections.map(c =>
          c.id === collectionId
            ? { ...c, assetIds: c.assetIds.filter(a => a !== assetId), updatedAt: Date.now() }
            : c
        ),
      })),

    createSmartCollection: (params: { name: string; smartQuery: SmartQuery; isAutoGenerated?: boolean }) =>
      get().createCollection({ name: params.name, type: 'smart', smartQuery: params.smartQuery, isAutoGenerated: params.isAutoGenerated ?? true }),

    refreshSmartCollection: (id: string) => {
      const collection = get().collections.find(c => c.id === id);
      if (!collection || collection.type !== 'smart' || !collection.smartQuery) return;

      // Gather all asset IDs that match the smart query
      const matchedAssetIds: string[] = [];
      const metadata = get().assetMetadata;
      const jobs = get().completedJobs;

      for (const asset of get().assetLibrary) {
        const assetMeta = metadata.get(asset.id);
        const generationContext = {
          prompt: asset.prompt,
          createdAt: asset.createdAt instanceof Date ? asset.createdAt.getTime() : undefined,
        };
        if (evaluateSmartQuery(collection.smartQuery!, generationContext, assetMeta)) {
          matchedAssetIds.push(asset.id);
        }
      }

      set((state) => ({
        collections: state.collections.map(c =>
          c.id === id ? { ...c, assetIds: matchedAssetIds, updatedAt: Date.now() } : c
        ),
      }));
    },

    analyzeAssets: (assetIds: string[]) => {
      set((state) => ({
        taggingQueue: [...state.taggingQueue, ...assetIds.filter(id => !state.taggingQueue.includes(id))],
      }));
    },

    setTaggingMode: (mode: TaggingMode) => set({ taggingMode: mode }),

    addUserTag: (tag: AssetTag) =>
      set((state) => ({
        availableTags: [...state.availableTags, { ...tag, source: 'user' as const }],
      })),

    removeUserTag: (tagId: string) =>
      set((state) => ({
        availableTags: state.availableTags.filter(t => !(t.id === tagId && t.source === 'user')),
      })),

    setActiveCollection: (id: string | null) => set({ activeCollectionId: id }),
  };
}