export type CollectionType = 'manual' | 'smart';
export type TaggingMode = 'on-generation' | 'background-batch' | 'on-demand' | 'off';

export interface Collection {
  id: string;
  name: string;
  description?: string;
  type: CollectionType;
  coverAssetId?: string;
  assetIds: string[];
  smartQuery?: SmartQuery;
  tagIds: string[];
  isAutoGenerated: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface SmartQuery {
  promptText?: string;
  model?: string;
  tags?: string[];
  dateRange?: { from: number; to: number };
  styleCategories?: string[];
  colorPalette?: string[];
  mood?: string[];
}

export interface AssetTag {
  id: string;
  name: string;
  category: 'style' | 'subject' | 'color' | 'mood' | 'custom';
  source: 'ai' | 'user';
  confidence: number;
}

export interface AssetMetadata {
  assetId: string;
  tags: AssetTag[];
  dominantColors: string[];
  colorNames: string[];
  detectedStyle: string[];
  detectedSubject: string[];
  detectedMood: string[];
  analyzedAt: number;
}