/**
 * Auto-update service over electron-updater (#34 installer PR4).
 *
 * The packaged app reads its feed from app-update.yml, generated by the
 * electron-builder `generic` publish config (Cloudflare R2 behind
 * updates.visionstudio.app - see docs/R2-DELIVERY.md). This service owns only
 * the check POLICY (an initial delay so first-run backend extraction wins the
 * disk/network, then a periodic re-check) and the honest status stream: every
 * status value comes from a real electron-updater event - there is no
 * synthetic progress anywhere. Installation happens on explicit user action
 * (`install()`) or silently on quit (autoInstallOnAppQuit); the app never
 * restarts itself unprompted.
 *
 * Disabled outside packaged builds and via VISION_STUDIO_DISABLE_UPDATES=1.
 * Updates install only when signed (win.verifyUpdateCodeSignature) - a
 * signature failure surfaces here as an honest `error` status.
 */

export interface UpdaterStatus {
  state:
    | 'disabled'
    | 'idle'
    | 'checking'
    | 'available'
    | 'not-available'
    | 'downloading'
    | 'downloaded'
    | 'error';
  version?: string;
  percent?: number;
  bytesPerSecond?: number;
  transferred?: number;
  total?: number;
  message?: string;
}

/** Structural subset of electron-updater's AppUpdater used by this service. */
export interface AutoUpdaterLike {
  autoDownload: boolean;
  autoInstallOnAppQuit: boolean;
  setFeedURL(options: { provider: 'generic'; url: string }): void;
  checkForUpdates(): Promise<unknown>;
  quitAndInstall(isSilent?: boolean, isForceRunAfter?: boolean): void;
  on(event: string, listener: (...args: never[]) => void): unknown;
}

interface UpdaterLogger {
  log: (...args: unknown[]) => void;
  warn: (...args: unknown[]) => void;
  error: (...args: unknown[]) => void;
}

export interface UpdaterServiceDependencies {
  autoUpdater: AutoUpdaterLike;
  isPackaged: boolean;
  env: NodeJS.ProcessEnv;
  getMainWindow: () => {
    webContents: { send: (channel: string, payload: unknown) => void };
  } | null;
  logger: UpdaterLogger;
}

// First check waits out app startup (backend spawn / first-run extraction own
// the disk and network right after launch); afterwards a long-lived session
// re-checks every 4 hours.
export const UPDATE_INITIAL_DELAY_MS = 15_000;
export const UPDATE_RECHECK_INTERVAL_MS = 4 * 60 * 60 * 1000;

const STATUS_CHANNEL = 'updater:status';

export function createUpdaterService({
  autoUpdater,
  isPackaged,
  env,
  getMainWindow,
  logger,
}: UpdaterServiceDependencies) {
  const enabled = isPackaged && env.VISION_STUDIO_DISABLE_UPDATES !== '1';

  let status: UpdaterStatus = enabled ? { state: 'idle' } : { state: 'disabled' };
  let initialTimer: ReturnType<typeof setTimeout> | null = null;
  let recheckTimer: ReturnType<typeof setInterval> | null = null;

  function setStatus(next: UpdaterStatus): void {
    status = next;
    try {
      getMainWindow()?.webContents.send(STATUS_CHANNEL, status);
    } catch (error) {
      // A torn-down window must never kill the check loop.
      logger.warn('updater: failed to push status to renderer', error);
    }
  }

  async function runCheck(): Promise<void> {
    try {
      await autoUpdater.checkForUpdates();
    } catch (error) {
      setStatus({
        state: 'error',
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }

  function start(): void {
    if (!enabled) {
      logger.log(
        'updater: disabled (' + (isPackaged ? 'VISION_STUDIO_DISABLE_UPDATES' : 'dev build') + ')',
      );
      return;
    }

    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = true;

    const feedOverride = env.VISION_STUDIO_UPDATE_URL;
    if (feedOverride) {
      // Staging/testing escape hatch; production reads app-update.yml.
      autoUpdater.setFeedURL({ provider: 'generic', url: feedOverride });
      logger.log(`updater: feed overridden to ${feedOverride}`);
    }

    autoUpdater.on('checking-for-update', () => {
      setStatus({ state: 'checking' });
    });
    autoUpdater.on('update-available', (info: { version?: string }) => {
      setStatus({ state: 'available', version: info?.version });
    });
    autoUpdater.on('update-not-available', (info: { version?: string }) => {
      setStatus({ state: 'not-available', version: info?.version });
    });
    autoUpdater.on(
      'download-progress',
      (progress: {
        percent?: number;
        bytesPerSecond?: number;
        transferred?: number;
        total?: number;
      }) => {
        setStatus({
          state: 'downloading',
          percent: progress?.percent,
          bytesPerSecond: progress?.bytesPerSecond,
          transferred: progress?.transferred,
          total: progress?.total,
        });
      },
    );
    autoUpdater.on('update-downloaded', (info: { version?: string }) => {
      setStatus({ state: 'downloaded', version: info?.version });
    });
    autoUpdater.on('error', (error: unknown) => {
      setStatus({
        state: 'error',
        message: error instanceof Error ? error.message : String(error),
      });
    });

    initialTimer = setTimeout(() => {
      void runCheck();
      recheckTimer = setInterval(() => {
        void runCheck();
      }, UPDATE_RECHECK_INTERVAL_MS);
    }, UPDATE_INITIAL_DELAY_MS);
  }

  function dispose(): void {
    if (initialTimer !== null) {
      clearTimeout(initialTimer);
      initialTimer = null;
    }
    if (recheckTimer !== null) {
      clearInterval(recheckTimer);
      recheckTimer = null;
    }
  }

  function getStatus(): UpdaterStatus {
    return status;
  }

  async function check(): Promise<UpdaterStatus> {
    if (!enabled) return status;
    await runCheck();
    return status;
  }

  function install(): void {
    if (status.state !== 'downloaded') {
      logger.warn(`updater: install requested in state '${status.state}' - ignoring`);
      return;
    }
    autoUpdater.quitAndInstall();
  }

  return { start, dispose, getStatus, check, install };
}
